name: Code Coverage

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@e37a97650feada694abb6420a84bbd23a71d6bb1
    with:
      python_version: '3.14'
      coverage_source: 'json_database'
      test_path: 'test/'
      install_extras: 'test'
      min_coverage: 80
      pr_comment: ${{ github.event_name == 'pull_request' }}
