permissions:
  contents: read

name: License Check

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  license_check:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-check.yml@02b4bf45467b832c0e03c2e15ed02daa584b8386 # dev
    with:
      python_version: '3.14'
      pr_comment: ${{ github.event_name == 'pull_request' }}
