permissions:
  contents: write
  pull-requests: write

name: Stable Release
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish_stable:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-stable.yml@02b4bf45467b832c0e03c2e15ed02daa584b8386 # dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
    with:
      branch: 'master'
      version_file: 'json_database/version.py'
      setup_py: 'setup.py'
      publish_release: true
      publish_pypi: false
      sync_dev: false

  publish_pypi:
    needs: publish_stable
    if: success()  # Ensure this job only runs if the previous job succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: dev
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.14"
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: version
        run: echo "::set-output name=version::$(python setup.py --version)"
        id: version
      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          password: ${{secrets.PYPI_TOKEN}}


  sync_dev:
    needs: publish_stable
    if: success()  # Ensure this job only runs if the previous job succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: master
      - name: Push master -> dev
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
