name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'json_database/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'readme.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'json_database/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.14"]
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v6
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel uv
      - name: Install test dependencies
        run: |
          uv pip install --system -r test/requirements.txt
      - name: Install core repo
        run: |
          uv pip install --system -e .
      - name: Run unittests with coverage
        run: |
          pytest --cov=json_database --cov-fail-under=80 --cov-report=term-missing --cov-report=xml test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.python-version == '3.14'
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
